version: "3.8"

services:
  postgres:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - 5433:5432
    networks:
      - app_network

  keycloak_postgres:
    image: postgres:latest
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  back:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/target
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - keycloak
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  keycloak_postgres_data:
