targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: cs|lib/src/api/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: cs|lib/src/api/graphql/schema.graphql