name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'app/**'
      - 'keycloak/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
      - 'app/**'
      - 'keycloak/**'

jobs:
  rust:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'server/') || github.event_name == 'pull_request' && contains(github.event.pull_request.head.ref, 'server/')
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Navigate to Rust directory and run tests
        run: |
          cd server
          cargo test

  flutter:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'app/') || github.event_name == 'pull_request' && contains(github.event.pull_request.head.ref, 'app/')
    name: Test Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: |
          cd app
          flutter pub get

      - name: Run Flutter tests
        run: |
          cd app
          flutter test --verbose

  