name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
      - 'app/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      app: ${{ steps.filter.outputs.app }}
    steps:
      - uses: actions/checkout@v3

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            server:
              - 'server/**'
            app:
              - 'app/**'

  rust:
    needs: detect_changes
    if: needs.detect_changes.outputs.server == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Test build
        run: cargo check

      - name: Test
        run: cargo test
      
      - name: Install docker
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:    ./server
          file:       ./server/Dockerfile
          push:       true
          tags:       youpidok/cs-rust-flutter:latest
          cache-from: type=registry,ref=youpidok/cs-rust-flutter:cache
          cache-to:   type=registry,ref=youpidok/cs-rust-flutter:cache,mode=max

  flutter:  
    needs: detect_changes
    if: needs.detect_changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy config.json.dist to config.json
        run: |
          cp config.json.dist config.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test test/test.dart
