name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
      - 'app/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      app: ${{ steps.filter.outputs.app }}
    steps:
      - uses: actions/checkout@v3

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            server:
              - 'server/**'
            app:
              - 'app/**'

  rust:
    needs: detect_changes
    if: needs.detect_changes.outputs.server == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Navigate to Rust directory and check compilation
        run: cargo check

      - name: Navigate to Rust directory and test compilation
        run: cargo test

  flutter:
    needs: detect_changes
    if: needs.detect_changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy config.json.dist to config.json
        run: |
          cp app/config.json.dist app/config.json

      - name: Copy config.json.dist to config.json
        run: |
          cp app/config.json.dist app/config.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: |
          cd app
          flutter pub get

#      - name: Run Flutter tests
#        run: |
#          cd app
#          flutter test --verbose
